SELECT * FROM alldata 
WHERE ((ACCOUNTID IS 17 OR TOACCOUNTID IS 17) AND TOACCOUNTID is NOT 18) AND TransactionType IS "Transfer"
UNION ALL
SELECT * FROM alldata WHERE CATEGID IS 26 AND AccountID is not 17
ORDER BY "Date"